export const LOCALES = [
  { name: 'Chinese (Simplified)', value: 'zh-CN' },
  { name: 'Chinese (Traditional)', value: 'zh-TW' },
  { name: 'English', value: 'en' },
  { name: 'Japanese', value: 'ja' },
  { name: 'Korean', value: 'ko' },
  { name: 'French', value: 'fr' },
  { name: 'German', value: 'de' },
  { name: 'Spanish', value: 'es' },
  { name: 'Italian', value: 'it' },
  { name: 'Portuguese', value: 'pt' },
  { name: 'Thai', value: 'th' },
  { name: 'Russian', value: 'ru' },
  { name: 'Arabic', value: 'ar' },
  { name: 'Indonesian', value: 'id' },
  { name: 'Vietnamese', value: 'vi' },
]
